reporting: "on"
startuppopupversion: 1
gui:
  mouseEvents: false
  showFileTree: false
git:
  autoFetch: false
  merging:
    args: --no-ff
  pagers:
    - useExternalDiffGitConfig: true
keybinding:
  universal:
    nextBlock: <tab>
